esphome:
  name: keypad

esp8266:
  board: nodemcuv2

# Enable logging
logger:

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

  ap:
    ssid: "Keypad Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

binary_sensor:
  - platform: gpio
    name: 1
    pin:
      number: D3
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 2
    pin:
      number: D4
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 3
    pin:
      number: D5
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 4
    pin:
      number: D6
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 5
    pin:
      number: D7
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 6
    pin:
      number: GPIO4
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 7
    pin:
      number: GPIO1
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 8
    pin:
      number: GPIO3
      mode: 
        input: true
        pullup: true
      inverted: true
  - platform: gpio
    name: 9
    pin:
      number: GPIO5
      mode: 
        input: true
        pullup: true
      inverted: true
